// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYFxwIRkviRg7z3JXi30q6J539QL8sHHk',
    appId: '1:289014446186:web:d7042a621d755fdd133213',
    messagingSenderId: '289014446186',
    projectId: 'e-commerceapp-530ea',
    authDomain: 'e-commerceapp-530ea.firebaseapp.com',
    storageBucket: 'e-commerceapp-530ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0JnaGos0YJ8G78n-SNCaAQwzfMEcsG24',
    appId: '1:289014446186:android:19e8a8b70026423c133213',
    messagingSenderId: '289014446186',
    projectId: 'e-commerceapp-530ea',
    storageBucket: 'e-commerceapp-530ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSGpa9bOC4dvwX7ObmQzzSDynyZarmz5w',
    appId: '1:289014446186:ios:d9fc589ec5acdd41133213',
    messagingSenderId: '289014446186',
    projectId: 'e-commerceapp-530ea',
    storageBucket: 'e-commerceapp-530ea.appspot.com',
    iosClientId: '289014446186-8p04r4gljvtu6f3l8qjr0dnq7se33hui.apps.googleusercontent.com',
    iosBundleId: 'com.example.eccommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSGpa9bOC4dvwX7ObmQzzSDynyZarmz5w',
    appId: '1:289014446186:ios:ed949493015ef944133213',
    messagingSenderId: '289014446186',
    projectId: 'e-commerceapp-530ea',
    storageBucket: 'e-commerceapp-530ea.appspot.com',
    iosClientId: '289014446186-6o90ehak8iq81j4n0shh7ke09rdkrlnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.eccommerce.RunnerTests',
  );
}
